# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import memoria_pb2 as memoria__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memoria_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MemoriaServidorStub(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.conectar = channel.unary_unary(
                '/agenda.MemoriaServidor/conectar',
                request_serializer=memoria__pb2.Jogador.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)


class MemoriaServidorServicer(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    def conectar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoriaServidorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'conectar': grpc.unary_unary_rpc_method_handler(
                    servicer.conectar,
                    request_deserializer=memoria__pb2.Jogador.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenda.MemoriaServidor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenda.MemoriaServidor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoriaServidor(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    @staticmethod
    def conectar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.MemoriaServidor/conectar',
            memoria__pb2.Jogador.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoriaClienteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.informarJogador = channel.unary_unary(
                '/agenda.MemoriaCliente/informarJogador',
                request_serializer=memoria__pb2.Jogo.SerializeToString,
                response_deserializer=memoria__pb2.Jogada.FromString,
                _registered_method=True)
        self.receberJogada = channel.unary_unary(
                '/agenda.MemoriaCliente/receberJogada',
                request_serializer=memoria__pb2.Jogo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.informarFimJogo = channel.unary_unary(
                '/agenda.MemoriaCliente/informarFimJogo',
                request_serializer=memoria__pb2.Jogo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)


class MemoriaClienteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def informarJogador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receberJogada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def informarFimJogo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoriaClienteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'informarJogador': grpc.unary_unary_rpc_method_handler(
                    servicer.informarJogador,
                    request_deserializer=memoria__pb2.Jogo.FromString,
                    response_serializer=memoria__pb2.Jogada.SerializeToString,
            ),
            'receberJogada': grpc.unary_unary_rpc_method_handler(
                    servicer.receberJogada,
                    request_deserializer=memoria__pb2.Jogo.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'informarFimJogo': grpc.unary_unary_rpc_method_handler(
                    servicer.informarFimJogo,
                    request_deserializer=memoria__pb2.Jogo.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenda.MemoriaCliente', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenda.MemoriaCliente', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoriaCliente(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def informarJogador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.MemoriaCliente/informarJogador',
            memoria__pb2.Jogo.SerializeToString,
            memoria__pb2.Jogada.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def receberJogada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.MemoriaCliente/receberJogada',
            memoria__pb2.Jogo.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def informarFimJogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.MemoriaCliente/informarFimJogo',
            memoria__pb2.Jogo.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
